In [1]:
# =============================================================================
# BASE IMPORTS, LOGGING SETUP
# =============================================================================
from trading.backtester.utils       import setup_logging
from trading.backtester.engine      import BacktestRunner, load_config, RunContext
from trading.backtester.performance import PerformanceReport

run = RunContext.create()

setup_logging(run_dir=run.run_dir)

backtest_config = load_config(file = 'default_backtest.yaml')

In [2]:
# =============================================================================
# STRATEGY CONSTRUCTION
# Replace ONLY this section when testing a different strategy
# =============================================================================

# 1. Import strategy + config
from trading.strategy_engine.strategies.directional import (
    MACrossover,
    MACrossoverConfig,
)

from trading.strategy_engine.features.trend import MAType


# 2. Define strategy parameters
strategy_config = MACrossoverConfig(
    fast_period=20,
    fast_type=MAType.EMA,
    slow_period=50,
    slow_type=MAType.SMA,
)


# 3. Build strategy object
strategy = MACrossover(strategy_config)

In [3]:
# =============================================================================
# RUN STRATEGY
# =============================================================================

run.save_configs(backtest_config, strategy_config)  

runner  = BacktestRunner(backtest_config, strategy)

try:
    results = runner.run()
    (run.run_dir / "SUCCESS").touch()

except Exception:
    (run.run_dir / "FAILED").touch()
    raise

2026-07-18 11:46:01 | INFO     | trading.backtester.engine.runner | Starting backtest run: MA_CROSS_ema_20_sma_50
2026-07-18 11:46:01 | INFO     | trading.backtester.engine.runner | Loaded 8760 bars from 2025-01-01 00:00:00+00:00 to 2025-12-31 23:00:00+00:00
2026-07-18 11:46:01 | INFO     | trading.backtester.engine.runner | Validated 8760 signals — no lookahead detected.
2026-07-18 11:46:01 | INFO     | trading.backtester.engine.runner | Phase 1 complete — 8760 bars, 215 signals.
2026-07-18 11:46:02 | INFO     | trading.backtester.engine.runner | Backtest complete: 8760 bars processed, final equity=30147.50

In [4]:
# =============================================================================
# RESULTS
# =============================================================================


report = PerformanceReport(results.portfolio_history)
### Save report here

report.display_report("BTCUSDT")

                             Value
Core
Symbol                     BTCUSDT
Interval                        1H
Start             2025-01-01 00:00
End               2025-12-31 23:00
Duration                  365 days
Bars                          8760
Starting Capital       $100,000.00
Final Capital           $30,147.50

                                      Value
Returns
CAGR                 -69.85%  ($-69,852.50)
Net Return           -69.85%  ($-69,852.50)
Gross Return         -61.49%  ($-61,488.96)
Sharpe (per bar)                     -2.531
Sharpe (annualised)                  -2.531
Sortino                              -3.413
Hit Rate (Trade)                     48.60%
Avg Win/Loss                          0.972
Expectancy                -0.01%  ($-12.76)
Profit Factor                         0.919
Skew                                 -0.703
Kurtosis                             14.440

                                        Value
Risk
Volatility                             43.68%
Max Drawdown           -72.00%  ($-72,004.11)
Max DD Duration                  8307.00 bars
Avg DD Duration                   784.91 bars
Time in Drawdown                       98.56%
Calmar                                 -0.970
VaR 95%                      0.68%  ($676.55)
VaR 99%                    1.39%  ($1,388.09)
CVaR 95%                   1.14%  ($1,143.47)
CVaR 99%                   2.07%  ($2,074.09)
Downside Deviation                     32.07%
Longest Losing Streak                 15 bars

                                      Value
Costs
Total Fee Drag         23.55%  ($23,554.98)
Total Funding Drag       -0.91%  ($-912.76)
Total Costs            24.47%  ($24,467.74)
Fee % of Net                         21.34%
Funding % of Net                     -0.83%
Cost % of Net                        22.17%
Cost to Gross Ratio                   0.285
Fee Drag (Sharpe)                     0.539
Funding Drag (Sharpe)                 0.021
Avg Fee per Bar              0.00%  ($2.69)
Annualised Turnover                  214.0x
% Bars Paying Funding                 6.77%

                                   Value
Position
Avg Position Size                 51.00%
Max Position Size                106.96%
Avg Long Size                     52.17%
Avg Short Size                   -51.09%
Time Long                         50.47%
Time Short                        48.28%
Time Flat                          1.26%
Time in Market                    98.74%
Avg Holding Period            40.46 bars
Largest Win           4.41%  ($4,411.09)
Largest Loss        -5.27%  ($-5,271.97)
Long PnL %                       -54.15%
Short PnL %                      -45.85%
Long Sharpe                       -2.788
Short Sharpe                      -2.314